alias app='bundle exec ruby app.rb'
alias tests='bundle exec ruby tests.rb'
alias console='bundle exec ruby console.rb'
alias webconsole='ruby w_console.rb'
alias dbconsole='d_console.rb'
alias logs='heroku logs'
alias rake_test_db='TEST=true rake db:migrate'
